python /workspace/yolov5/val.py \
    --data /workspace/project/data/dataset.yaml \
    --weights /workspace/project/runs/train/model02/weights/best.pt \
    --batch-size 14 \
    --imgsz 1280 \
    --conf-thres 0.363 \
    --iou-thres 0.6 \
    --task test \
    --device 0 \
    --verbose \
    --name model02